### ISSUE TITLE
setting 3 way valve position.

### ISSUE THREAD

**Issue by nebduj** [djtimca/omnilogic-api#19]
More of a Feature Request than an issue, but I don't see a way to handle 3-way valves.  There is on/off but not position 1/2.  See the excerpt from the Config data:

            "Filter": {
                "Alarms": [],
                "Filter-Type": "FMT_VARIABLE_SPEED_PUMP",
                "Max-Pump-RPM": "3450",
                "Max-Pump-Speed": "100",
                "Min-Pump-RPM": "800",
                "Min-Pump-Speed": "25",
                "Name": "Filter Pump",
                "Priming-Enabled": "yes",
                "Shared-Type": "BOW_SHARED_EQUIPMENT",
                "filterSpeed": "0",
                "filterState": "0",
                "lastSpeed": "50",
                "systemId": "3",
                **"valvePosition": "2"**
            }

I tried using the set_relay_valve function, but it actually sets the pump speed instead of impacting the valve position..

**Comment by nebduj** [comment]
I found that it is possible to move the valve position by starting the virtual pump attached to the other valve position.  Perhaps that's the best way to do it, if not intuitive.

**Comment by djtimca** [comment]
Sorry for long delay in reply. Indeed many things related to this integration are not exactly intuitive.

**Comment by djtimca** [comment]
Assuming that you have solved this with the virtual pump. If there is something else required feel free to provide additional information and reopen.
