### ISSUE TITLE
Support for Themes would a nice feature

### ISSUE THREAD

**Issue by nebduj** [djtimca/omnilogic-api#20]
Omnilogic lets one save "Theme's" that allow for one command to put the pool into different modes.  These seem to be coming through in the output as a "Group" but I can't be sure.  In the returned JSON I see the groupState changing when I enable and disable the theme using the app.  I tried setting the groupState using the set_relay command but it didn't seem to have any impact.

            "Group": {
                "groupState": "0",
                "systemId": "24"
            },

**Comment by djtimca** [comment]
I don't believe there is an option to set themes through the API. Since this API was designed to support the Home Assistant integration, Home Assistant has it's own scripts/themes which would replace the need for the native Omnilogic themes. Not something I'll add here.
