### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [djtimca/omnilogic-api#28]
Could you please tag the source? This allows distributions to get the complete source from GitHub if they want.

This was done till 0.4.6

Thanks

**Comment by djtimca** [comment]
Not sure what's missing - nothing has been removed from the package since 0.4.6 and when I browse at PyPi the GitHub is linked. Can you clarify what you need?

**Comment by cryptk** [comment]
I think the concern is that the version on pypy is 0.4.9, but the latest tag on the repo is 0.4.6.  This makes it difficult to check out the git repo with the same code that was published to pypy for versions 0.4.7, 0.4.8 and 0.4.9.

**Comment by djtimca** [comment]
Ah! Perfect - thanks! Will do!

**Comment by djtimca** [comment]
Added 0.4.9 release and will continue this going forward.
