### ISSUE TITLE
Pool Chlorinator Salt Level should be long-term statistic

### ISSUE THREAD

**Issue by MHillyer** [djtimca/omnilogic-api#29]
The sensor.chlorinator_salt_level should be a long term statistic so it can be graphed.

**Comment by MHillyer** [comment]
Perhaps a related issue then:

My chlorinator was added last week, I see a report of No History Found when I open it. Is that maybe an issue with it being added after the fact into the integration?

**Comment by djtimca** [comment]
Shouldn't be... do you have history on everything else? Are you running the standard Home Assistant database? Maybe check: https://community.home-assistant.io/t/no-state-history-found-how-do-i-get-it-back/168449

**Comment by MHillyer** [comment]
A couple of reboots and it seems I’m back in action, thanks.

Sent from a mobile device.
________________________________
