### ISSUE TITLE
Do I have to use asyncio?

### ISSUE THREAD

**Issue by AlexMaghen** [djtimca/omnilogic-api#34]
Thanks for this excellent library. I tried to just do this...

```
api_client = OmniLogic("alex@maghen.com", "Mayim1234!")
telemetry_data = api_client.get_telemetry_data()
log.debug(telemetry_data)
```

and I got this runtime error...

```
<coroutine object OmniLogic.get_telemetry_data at 0x7f9c573ac0>
sys:1: RuntimeWarning: coroutine 'OmniLogic.get_telemetry_data' was never awaited
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f9d5eef10>
```

I'm not familiar with asyncio - do I have to use it to make these calls?

Thanks!

Alex

**Comment by AlexMaghen** [comment]
Ugh! What an idiot I am!!! Thanks.

On Jun 26, 2023, at 13:48, James ***@***.***> wrote:

﻿

Hello @AlexMaghen<https://github.com/AlexMaghen>! I just wanted to jump in and recommend that you immediately change your password as you have potentially accidentally included it in the issue (editing the comment will keep the history). If it's a dummy password, then you can forgive me.

In future, I would recommend changing credential values when posting online to something generic (eg "EMAIL" and "PASSWORD") instead of an actual email/password. Hope that helps 🙂

**Comment by djtimca** [comment]
You can see how we utilize the API calls for Home Assistant at https://github.com/djtimca/haomnilogic

You do need to use Async for this library.
